name: test-aws

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    environment: aws   # <-- IMPORTANT !!!

    steps:
      - uses: actions/checkout@v3

      - name: DEBUG region
        run: |
          echo ">>>> DEBUG: secret AWS_REGION length:"
          if [ -z "${{ secrets.AWS_REGION }}" ]; then
            echo "AWS_REGION is EMPTY"
          else
            echo "AWS_REGION=${{ secrets.AWS_REGION }}"
          fi

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
